image: public.ecr.aws/docker/library/python:3.8

stages:
  - test
  - profile

run_tests:
  stage: test
  resource_group: ssh-helper-tests
  script:
    - bash run_tests.sh
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: tests/pytest_report.xml
      coverage_report:
        coverage_format: cobertura
        path: tests/coverage.xml
    paths:
      - src_diff_main.txt
      - src_diff_latest.txt
      - pip_freeze_before.txt
      - pip_freeze_after.txt
      - pip_freeze_diff.txt
      - pip_freeze_after_test.txt
      - pip_freeze_diff_test.txt
      - tests/pytest_report.xml
      - tests/pytest_report.html
      - tests/htmlcov/
      - tests/coverage.xml
      - tests/.coverage
      - bandit.txt
      - flake8.txt

profile_tests:
  stage: profile
  resource_group: ssh-helper-tests
  script:
    - bash profile_tests.sh
  artifacts:
    when: always
    paths:
      - tests/prof/